version: '3'

services:

  postgres-db:
    container_name: postgres-db-container
    image: postgres:10.5
    expose:
      - 5432
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgres-db-volume
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=storage
    restart: unless-stopped
    
  jetty-server:
    container_name: jetty-server-storage
    build: 
      context: .
    image: jetty-storage-app:latest
    expose:
      - 8080
    ports: 
      - "127.0.0.1:8080:8080"
    environment:
      - DB_URL=postgres-db
    depends_on:
      - postgres-db
    links:
      - postgres-db

volumes:
  postgres-db-volume:
 